sudo: required
language: node_js
node_js:
  -  "0.12"
install:
  - curl https://install.meteor.com | /bin/sh
  - npm install -g spacejam
before_script:
  - meteor --version
script:
  - spacejam test-packages ./
